version: '3'

services:
  app:
    build:
      context: ./application
    restart: always
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URI: postgresql+psycopg2://app_user:app_password@db/app_db
    depends_on:
      - db
      - redis
    networks:
      - backend
    volumes:
      - ./app:/app
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - backend
      - frontend
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./app/static:/var/www/html

    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email ahmed.sramadan89@gmail.com --agree-tos --no-eff-email -d 3.121.200.138 -d *.3.121.200.138

volumes:
  db-data:

networks:
  backend:
  frontend:
