version: '3'

services:
  app:
    build:
      context: ./application
    restart: always
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URI: postgresql+psycopg2://readonly:readonlypassword@db/mydb
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    networks:
      - backend
    volumes:
      - ./app:/app
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  readonly_user:
    image: postgres
    command: "postgres -c max_connections=200 -c shared_buffers=256MB -c max_wal_senders=3 -c wal_level=replica"
    environment:
      POSTGRES_USER: readonly
      POSTGRES_PASSWORD: readonlypassword
      POSTGRES_DB: mydb
    networks:
      - backend
  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
