version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URI: postgresql+psycopg2://app_user:app_password@db:5432/app_db
    depends_on:
      - db
      - redis
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:6
    command: redis-server --requirepass mysecretpassword
    volumes:
      - redis-data:/data
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - certbot-data:/var/www/certbot
      - nginx-data:/etc/nginx/

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path /var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d app.sofed.io
    volumes:
      - certbot-data:/var/www/certbot
      - nginx-data:/etc/nginx/
    depends_on:
      - nginx
    entrypoint: /bin/sh -c "trap : TERM INT; sleep infinity & wait"

volumes:
  db-data:
  redis-data:
  certbot-data:
  nginx-data:
